### ISSUE TITLE
records not sent to kafka

### ISSUE THREAD

**Issue by npradeep357** [srijiths/kafka-connectors#1]
started this connector using connect-standalone with valid properties.  Messages are not sent to kafka.

**Comment by srijiths** [comment]
Can you please provide more information ? Is JMX enabled in your kafka instances ?

**Comment by srijiths** [comment]
@npradeep357 can you update the ticket ?

**Comment by srijiths** [comment]
closing this. Not able to re produce. No updates from @npradeep357
